name: APK Oluştur ve Dağıt

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v2

      - name: Node.js Kurulumu
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 16.13.2

      - name: Python Kurulumu
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Bağımlılıkları Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            python3-pip
          pip install kivy
          pip install buildozer

      - name: APK Oluştur
        run: |
          buildozer -v android debug

      - name: APK'yi Yayına Yükle
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: ./bin/*.apk
