name: Build and Deploy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          node-version: 
              -16.x

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            python3-pip
          pip install kivy
          pip install buildozer

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK to Releases
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: ./bin/*.apk
